// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using minipdv.Infrastructure.Data.Context;

#nullable disable

namespace minipdv.Migrations
{
    [DbContext(typeof(MiniPDVContext))]
    [Migration("20260527011039_MakeCodBarraInteger")]
    partial class MakeCodBarraInteger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("minipdv.Domain.Entities.Base.AbstractUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ContatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId")
                        .IsUnique()
                        .HasFilter("[ContatoId] IS NOT NULL");

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("AbstractUsuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Fabricante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int?>("ContatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId")
                        .IsUnique()
                        .HasFilter("[ContatoId] IS NOT NULL");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.PrincipioAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("PrincipiosAtivos");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CodBarra")
                        .HasColumnType("int");

                    b.Property<bool>("Controlado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Dosagem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FabricanteId")
                        .HasColumnType("int");

                    b.Property<int>("PrincipioAtivoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoGrupoId")
                        .HasColumnType("int");

                    b.Property<string>("RegistroMS")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FabricanteId");

                    b.HasIndex("PrincipioAtivoId");

                    b.HasIndex("ProdutoGrupoId");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<bool>("Controlado").HasValue(false);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoCodBarra", b =>
                {
                    b.Property<int>("CodBarra")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("CodBarra");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoCodBarras");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoEstoque", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Lote")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Fabricacao")
                        .HasColumnType("date");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Validade")
                        .HasColumnType("date");

                    b.HasKey("ProdutoId", "Lote");

                    b.ToTable("ProdutoEstoques");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ProdutoGrupos");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ProdutoTipos");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Farmaceutico", b =>
                {
                    b.HasBaseType("minipdv.Domain.Entities.Base.AbstractUsuario");

                    b.Property<string>("Crf")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasDiscriminator().HasValue("Farmaceutico");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Usuario", b =>
                {
                    b.HasBaseType("minipdv.Domain.Entities.Base.AbstractUsuario");

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoControlado", b =>
                {
                    b.HasBaseType("minipdv.Domain.Entities.Produto");

                    b.Property<string>("ClasseTerapeutica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue(true);
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Base.AbstractUsuario", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Contato", "Contato")
                        .WithOne()
                        .HasForeignKey("minipdv.Domain.Entities.Base.AbstractUsuario", "ContatoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contato");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Fabricante", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Contato", "Contato")
                        .WithOne()
                        .HasForeignKey("minipdv.Domain.Entities.Fabricante", "ContatoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contato");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Produto", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Fabricante", "Fabricante")
                        .WithMany("Produtos")
                        .HasForeignKey("FabricanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("minipdv.Domain.Entities.PrincipioAtivo", "PrincipioAtivo")
                        .WithMany("Produtos")
                        .HasForeignKey("PrincipioAtivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("minipdv.Domain.Entities.ProdutoGrupo", "Grupo")
                        .WithMany("Produtos")
                        .HasForeignKey("ProdutoGrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabricante");

                    b.Navigation("Grupo");

                    b.Navigation("PrincipioAtivo");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoCodBarra", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Produto", "Produto")
                        .WithMany("CodBarras")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoEstoque", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Produto", "Produto")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Fabricante", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.PrincipioAtivo", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Produto", b =>
                {
                    b.Navigation("CodBarras");

                    b.Navigation("Estoques");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoGrupo", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
