// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using minipdv.Infrastructure.Data.Context;

#nullable disable

namespace minipdv.Migrations
{
    [DbContext(typeof(MiniPDVContext))]
    [Migration("20260530141743_CreateVendaAndAdjustProdutoEstoque")]
    partial class CreateVendaAndAdjustProdutoEstoque
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("minipdv.Domain.Entities.Base.AbstractUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ContatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId")
                        .IsUnique()
                        .HasFilter("[ContatoId] IS NOT NULL");

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("AbstractUsuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ContatoId")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId")
                        .IsUnique()
                        .HasFilter("[ContatoId] IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Fabricante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int?>("ContatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId")
                        .IsUnique()
                        .HasFilter("[ContatoId] IS NOT NULL");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Prescritor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Conselho")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Numero", "Conselho", "Uf")
                        .IsUnique();

                    b.ToTable("Prescritores", (string)null);
                });

            modelBuilder.Entity("minipdv.Domain.Entities.PrincipioAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("PrincipiosAtivos");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CodBarra")
                        .HasColumnType("int");

                    b.Property<bool>("Controlado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Dosagem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FabricanteId")
                        .HasColumnType("int");

                    b.Property<int>("PrincipioAtivoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoGrupoId")
                        .HasColumnType("int");

                    b.Property<string>("RegistroMS")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FabricanteId");

                    b.HasIndex("PrincipioAtivoId");

                    b.HasIndex("ProdutoGrupoId");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<bool>("Controlado").HasValue(false);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoCodBarra", b =>
                {
                    b.Property<int>("CodBarra")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("CodBarra");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoCodBarras");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoEstoque", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Lote")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Fabricacao")
                        .HasColumnType("date");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("RegistroMS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Validade")
                        .HasColumnType("date");

                    b.HasKey("ProdutoId", "Lote");

                    b.ToTable("ProdutoEstoques");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ProdutoGrupos");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ProdutoTipos");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("PrescritorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("PrescritorId");

                    b.ToTable("Receitas", (string)null);
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ReceitaProdutoEstoque", b =>
                {
                    b.Property<int>("ReceitaId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ReceitaId", "ProdutoId", "Lote");

                    b.HasIndex("ProdutoId", "Lote");

                    b.ToTable("ReceitaProdutoEstoque");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReceitaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("Vendas", (string)null);
                });

            modelBuilder.Entity("minipdv.Domain.Entities.VendaProdutoEstoque", b =>
                {
                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("VendaId", "ProdutoId", "Lote");

                    b.HasIndex("ProdutoId", "Lote");

                    b.ToTable("VendaProdutoEstoque");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("minipdv.Domain.Entities.Base.AbstractUsuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Farmaceutico", b =>
                {
                    b.HasBaseType("minipdv.Domain.Entities.Base.AbstractUsuario");

                    b.Property<string>("Crf")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasDiscriminator().HasValue("Farmaceutico");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Usuario", b =>
                {
                    b.HasBaseType("minipdv.Domain.Entities.Base.AbstractUsuario");

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoControlado", b =>
                {
                    b.HasBaseType("minipdv.Domain.Entities.Produto");

                    b.Property<string>("ClasseTerapeutica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue(true);
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Base.AbstractUsuario", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Contato", "Contato")
                        .WithOne()
                        .HasForeignKey("minipdv.Domain.Entities.Base.AbstractUsuario", "ContatoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contato");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Contato", "Contato")
                        .WithOne()
                        .HasForeignKey("minipdv.Domain.Entities.Cliente", "ContatoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contato");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Fabricante", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Contato", "Contato")
                        .WithOne()
                        .HasForeignKey("minipdv.Domain.Entities.Fabricante", "ContatoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contato");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Produto", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Fabricante", "Fabricante")
                        .WithMany("Produtos")
                        .HasForeignKey("FabricanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("minipdv.Domain.Entities.PrincipioAtivo", "PrincipioAtivo")
                        .WithMany("Produtos")
                        .HasForeignKey("PrincipioAtivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("minipdv.Domain.Entities.ProdutoGrupo", "Grupo")
                        .WithMany("Produtos")
                        .HasForeignKey("ProdutoGrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabricante");

                    b.Navigation("Grupo");

                    b.Navigation("PrincipioAtivo");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoCodBarra", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Produto", "Produto")
                        .WithMany("CodBarras")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoEstoque", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Produto", "Produto")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Receita", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Cliente", "Comprador")
                        .WithMany()
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("minipdv.Domain.Entities.Cliente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("minipdv.Domain.Entities.Prescritor", "Prescritor")
                        .WithMany()
                        .HasForeignKey("PrescritorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Paciente");

                    b.Navigation("Prescritor");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ReceitaProdutoEstoque", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Receita", "Receita")
                        .WithMany("ReceitaProdutoEstoques")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("minipdv.Domain.Entities.ProdutoEstoque", "ProdutoEstoque")
                        .WithMany("ReceitaProdutoEstoques")
                        .HasForeignKey("ProdutoId", "Lote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoEstoque");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Session", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Venda", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("minipdv.Domain.Entities.Receita", "Receita")
                        .WithMany()
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.VendaProdutoEstoque", b =>
                {
                    b.HasOne("minipdv.Domain.Entities.Venda", "Venda")
                        .WithMany("VendaProdutoEstoques")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("minipdv.Domain.Entities.ProdutoEstoque", "ProdutoEstoque")
                        .WithMany("VendaProdutoEstoques")
                        .HasForeignKey("ProdutoId", "Lote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoEstoque");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Fabricante", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.PrincipioAtivo", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Produto", b =>
                {
                    b.Navigation("CodBarras");

                    b.Navigation("Estoques");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoEstoque", b =>
                {
                    b.Navigation("ReceitaProdutoEstoques");

                    b.Navigation("VendaProdutoEstoques");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.ProdutoGrupo", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Receita", b =>
                {
                    b.Navigation("ReceitaProdutoEstoques");
                });

            modelBuilder.Entity("minipdv.Domain.Entities.Venda", b =>
                {
                    b.Navigation("VendaProdutoEstoques");
                });
#pragma warning restore 612, 618
        }
    }
}
